Checking ci/cd

diff --git a/.github/workflows/deploy-to-render.yml b/.github/workflows/deploy-to-render.yml
--- a/.github/workflows/deploy-to-render.yml
+++ b/.github/workflows/deploy-to-render.yml
@@ -21,7 +21,10 @@ jobs:
       - name: Check registry.render.com connectivity
         run: curl -sL registry.render.com && echo "Host reachable" || echo "Host unreachable"
 
-      # Step 3: Log in to Render's Private Registry
+      - name: Check general network connectivity
+        run: curl -sL google.com && echo "General internet access - OK" || echo "General internet access - Failed"
+      
+        # Step 3: Log in to Render's Private Registry
       - name: Log in to Render Registry
         run: docker login registry.render.com -u render -p ${{ secrets.RENDER_API_KEY }}
         
